### ISSUE TITLE
I can't install Elm-UI on Linux (Ubuntu)

### ISSUE THREAD

**Issue by webrune-tim** [gdotdesign/elm-ui#60]
Here is the npm error from `sudo npm install -g elm-ui`:

...
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.8.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "elm-ui"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! path /usr/lib/node_modules/elm-ui/bin/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/elm-ui/bin/index.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/elm-ui/bin/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tithos/Web/Elm/npm-debug.log
`

Is linux support in the works?

**Comment by gdotdesign** [comment]
Since 1.0.0 Elm-UI no longer has an NPM package. If you are looking for the development environment that the NPM package offered you can check out https://github.com/gdotdesign/elm-dev-env.

If you found a reference to it somewhere in the documentation let me know. 

You can read more about how to use Elm-UI it in the guide: http://elm-ui.info/documentation/getting-started/setup
